### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aurelienpierre** [ptman/remarkable-docker#1]
Hi !

how do you install this as a container ? The commands you gave fail with:

```
Unable to find image 'remarkable:latest' locally
docker: Error response from daemon: repository remarkable not found: does not exist or no pull access.
See 'docker run --help'.

```

I'm not a docker user, I have no previous experience with it.

Thanks.

**Comment by ptman** [comment]
I see. The trouble is with the last parameter to docker run. `remarkable` refers to a docker image by the name `remarkable`. You can check your docker images using `docker images`. You can either build the image by the name remarkable using `docker build -t remarkable .` or you can change that last argument `remarkable` to docker run to `ptman/remarkable`. I'll update the readme.

**Comment by ptman** [comment]
https://github.com/ptman/remarkable-docker/commit/7a2b4f51fc410f2164e877ff785afcccea7e38ac

**Comment by aurelienpierre** [comment]
Ok, it's the `docker build -t remarkable .` that was missing. Thanks a lot !

**Comment by ptman** [comment]
No worries. HTH HAND
