### ISSUE TITLE
X11 forwarding request failed on channel 0

### ISSUE THREAD

**Issue by damienchallet** [ptman/remarkable-docker#3]
When I run this (in a proper X11 environment)

    $ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 -Y -l remarkable localhost /opt/remarkable/reMarkable

I get this output

```
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
X11 forwarding request failed on channel 0
Environment:
  LC_PAPER=en_US.UTF-8
  LC_ADDRESS=en_US.UTF-8
  LC_MONETARY=en_US.UTF-8
  LC_NUMERIC=en_US.UTF-8
  LC_TELEPHONE=en_US.UTF-8
  LC_IDENTIFICATION=en_US.UTF-8
  LANG=en_US.UTF-8
  LC_MEASUREMENT=en_US.UTF-8
  LC_TIME=en_US.UTF-8
  LC_NAME=en_US.UTF-8
  USER=remarkable
  LOGNAME=remarkable
  HOME=/home/remarkable
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
  MAIL=/var/mail/remarkable
  SHELL=/bin/bash
  SSH_CLIENT=172.17.0.1 53760 22
  SSH_CONNECTION=172.17.0.1 53760 172.17.0.2 22
QML debugging is enabled. Only use this in a safe environment.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-remarkable'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

Any help would be welcome !

Thanks in advance

**Comment by ptman** [comment]
`X11 forwarding request failed` ? Have you disabled X11 forwarding in some config?

**Comment by damienchallet** [comment]
I have followed the instructions and not modified anything. I tried to pull
again today, but I am using the latest version.

Should I rebuilt the image myself and try to modifier sshd daemon config of
the docker image ?

**Comment by ptman** [comment]
Please try anything and everything and tell me what worked. But I doubt changing the image is needed since the same exact image works for others.

**Comment by damienchallet** [comment]
Yes, that is weird, and I use Ubuntu 16.04.

I see this in my logs:

debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_global_request: rtype no-more-sessions@openssh.com
want_reply 0
debug1: server_input_channel_req: channel 0 request x11-req reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req x11-req
Failed to allocate internet-domain X11 display socket.
debug1: x11_create_display_inet failed.
debug1: server_input_channel_req: channel 0 request env reply 0
debug1: session_by_channel: session 0 channel 0

Anyway, I will use the web interface for a while and try again in a few
weeks. Many thanks for your answer.

**Comment by ptman** [comment]
BTW, try replacing `-Y` with `-X`. Also, do you have `xauth` installed?

**Comment by damienchallet** [comment]
I have already tried that, and xauth is installed. I have checked that I
can ssh -X programs from other hosts and to other hosts. Nevermind.
Something in my config must be non-standard, so I will try again with a
vanilla image!

**Comment by takuyozora** [comment]
Maybe this can help : #6 
If ssh forwarding is not working you can extract the app from the container and run it on your system.

**Comment by mac-l1** [comment]
@damienchallet and others: i have exactly the same issue with a fresh installed ubuntu 16.04; have you already found a solution? would be great!

**Comment by damienchallet** [comment]
I do: use flatpack .

**Comment by ptman** [comment]
Right, flatpak is indeed superior.
