### ISSUE TITLE
File import

### ISSUE THREAD

**Issue by ptman** [ptman/remarkable-docker#4]
When trying to Import files, nothing happens and there is a message on the console:

    ERROR: No native FileDialog implementation available.
    Qt Labs Platform requires Qt Widgets on this setup.
    Add 'QT += widgets' to .pro and create QApplication in main().

I'm not sure which package/dependency is still missing.

**Comment by saitiku** [comment]
have the same issue. Cannot upload any files at all. Drag and drop does not work.

**Comment by takuyozora** [comment]
Maybe this can help : #6 

Document upload works fine for me (tested with drag'n'drop)
