### ISSUE TITLE
Workaround : extract app and run it outside docker

### ISSUE THREAD

**Issue by takuyozora** [ptman/remarkable-docker#6]
Bonsoir,

I use the ReMarkable tablet a lot since I got one, but the lack of Linux support is a shame.. 
Thanks you for this repo and the docker image, if you have some difficulties with it you can extract the app and run it outside the container.

```bash
# Create app destination directory
sudo mkdir /opt/remarkable
mkdir /tmp/remarkable
# Launch the container : 
docker run --rm -p 127.0.0.1:2222:22 -v /tmp/remarkable/:/home/remarkable/ ptman/remarkable
# Enter the container :
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 -Y -l remarkable localhost
# .. from inside the container ..
cp -a /opt/remarkable/* /home/remarkable
exit
# .. from the host ..
cd /opt/remarkable
sudo cp -a /tmp/remarkable/* ./
# Check the deps
ldd reMarkable
# Install missing lib if any
# Then run the app
./reMarkable
```

It works for me. I hope that can help others.

Olivier.

**Comment by ptman** [comment]
Why would you extract the app from the container when the URL to download it can be found at https://github.com/ptman/remarkable-docker/blob/master/Dockerfile#L7 ?

**Comment by takuyozora** [comment]
Maybe because it was late and I was in a 'rush'.
Sorry for the noise.

Do you now if there is some new versions of the soft ?

**Comment by ptman** [comment]
No idea, the links on https://remarkable.engineering/ disappeared
